const R="aepuns/aepuns.github.io",P="data/updates.json",B="main",q=s=>document.querySelector(s);let t="",sha="",posts=[];
const msg=(e,x)=>e.textContent=x;
function draw(){const f=q("#updates-feed");f.replaceChildren();if(!posts.length)return msg(q("#updates-status"),"No updates yet.");msg(q("#updates-status"),"");posts.forEach(x=>{let a=document.createElement("article"),d=document.createElement("time"),h=document.createElement("h2"),p=document.createElement("p");a.className="update-entry";d.textContent=new Date(x.published_at).toLocaleDateString();h.textContent=x.title;p.textContent=x.body;a.append(d,h,p);if(x.attachment){let i=new Image;i.src=x.attachment.path;i.alt=x.attachment.name;a.append(i)}f.append(a)})}
async function load(){try{let r=await fetch(P+"?v="+Date.now()),j=await r.json();posts=j.updates||[];draw()}catch{msg(q("#updates-status"),"Updates are unavailable right now.")}}load();
function open(){q("#admin-dialog").showModal();q("#github-token").focus()}let s="";document.addEventListener("keydown",e=>{s+=e.key;s=s.slice(-10);if(s.endsWith("apnArrowUp"))open()});q("#admin-close").onclick=()=>q("#admin-dialog").close();
let hold;q("#updates-title").addEventListener("pointerdown",()=>{hold=setTimeout(open,800)});["pointerup","pointerleave","pointercancel"].forEach(type=>q("#updates-title").addEventListener(type,()=>clearTimeout(hold)));
q("#login-form").onsubmit=async e=>{e.preventDefault();t=q("#github-token").value;let r=await fetch(`https://api.github.com/repos/${R}/contents/${P}?ref=${B}`,{headers:{Authorization:`Bearer ${t}`}});if(!r.ok)return msg(q("#login-status"),"Token needs Contents read and write access.");let j=await r.json();sha=j.sha;posts=JSON.parse(atob(j.content)).updates||[];q("#login-form").hidden=true;q("#update-form").hidden=false;msg(q("#login-status"),"sign-in confirmed.")};
q("#update-form").onsubmit=async e=>{e.preventDefault();let title=q("#update-title").value.trim(),body=q("#update-body").value.trim();if(!title||!body)return;posts.unshift({id:crypto.randomUUID(),title,body,published_at:new Date().toISOString()});let content=btoa(unescape(encodeURIComponent(JSON.stringify({updates:posts},null,2)))),r=await fetch(`https://api.github.com/repos/${R}/contents/${P}`,{method:"PUT",headers:{Authorization:`Bearer ${t}`,"Content-Type":"application/json"},body:JSON.stringify({message:"Update site news",branch:B,sha,content})});if(!r.ok)return msg(q("#admin-status"),"Could not save update.");sha=(await r.json()).content.sha;q("#update-form").reset();draw();msg(q("#admin-status"),"posted.")};
q("#admin-sign-out").onclick=()=>{t="";q("#admin-dialog").close()};
