-- Run this once in the Supabase SQL Editor.
-- Likes also require "Allow anonymous sign-ins" in
-- Authentication > Sign In / Providers > Anonymous Sign-Ins.

create table if not exists public.updates (
    id bigint generated by default as identity primary key,
    title text not null check (char_length(btrim(title)) between 1 and 120),
    body text not null check (char_length(btrim(body)) between 1 and 5000),
    published_at timestamptz not null default now(),
    author_id uuid not null default auth.uid() references auth.users(id)
);

alter table public.updates enable row level security;

grant select (id, title, body, published_at) on public.updates to anon, authenticated;
grant insert (title, body) on public.updates to authenticated;
grant delete on public.updates to authenticated;
grant usage, select on sequence public.updates_id_seq to authenticated;

drop policy if exists "Updates are public" on public.updates;
create policy "Updates are public"
on public.updates
for select
to anon, authenticated
using (true);

drop policy if exists "Only the site owner can post updates" on public.updates;
create policy "Only the site owner can post updates"
on public.updates
for insert
to authenticated
with check (
    auth.uid() = '8951dc95-5cbf-4800-941a-679902d34849'::uuid
    and author_id = auth.uid()
);

drop policy if exists "Only the site owner can delete updates" on public.updates;
create policy "Only the site owner can delete updates"
on public.updates
for delete
to authenticated
using (
    auth.uid() = '8951dc95-5cbf-4800-941a-679902d34849'::uuid
    and author_id = auth.uid()
);

create table if not exists public.update_likes (
    update_id bigint not null references public.updates(id) on delete cascade,
    user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
    created_at timestamptz not null default now(),
    primary key (update_id, user_id)
);

alter table public.update_likes enable row level security;

grant select (update_id, user_id) on public.update_likes to anon, authenticated;
grant insert (update_id) on public.update_likes to authenticated;
grant delete on public.update_likes to authenticated;

drop policy if exists "Likes are public" on public.update_likes;
create policy "Likes are public"
on public.update_likes
for select
to anon, authenticated
using (true);

drop policy if exists "Users can add their own likes" on public.update_likes;
create policy "Users can add their own likes"
on public.update_likes
for insert
to authenticated
with check (user_id = (select auth.uid()));

drop policy if exists "Users can remove their own likes" on public.update_likes;
create policy "Users can remove their own likes"
on public.update_likes
for delete
to authenticated
using (user_id = (select auth.uid()));
